packages: []

catalogs:
  build:
    '@ai-sdk/google': ^1.2.18
    '@nuxt/devtools': ^2.3.2
    '@nuxt/eslint': ^1.3.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.10.1
    '@unocss/eslint-config': ^66.1.2
    '@unocss/nuxt': ^66.1.2
    '@vite-pwa/nuxt': ^1.0.0
    '@vueuse/nuxt': ^13.1.0
    ai: ^4.3.16
    nuxt: ^3.16.2
    turndown: ^7.2.0
    unocss: ^66.1.2
    unplugin: ^2.2.2
    vite: ^6.2.5

  dev:
    '@antfu/eslint-config': ^4.11.0
    eslint: ^9.24.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.8
    zod: ^3.25.36

  frontend:
    '@vueuse/core': ^13.1.0
    '@webcontainer/api': ^1.6.1
    '@xterm/xterm': ^5.5.0
    pinia: ^3.0.1
    vue: ^3.5.13

  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/cil': ^1.2.2
    '@iconify-json/twemoji': ^1.2.2

  types:
    '@types/node': ^20.5.0
    '@types/turndown': ^5.0.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
